### ISSUE TITLE
Support discussing mappings

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#532] opened 2019-12-17 07:20 UTC
Adding support of discussing mappings may be useful but also distracting. To keep things simple, only mappings should be commented, so all comments on a given mapping show up as a single list. Still such feature raises a lot of questions e.g. how to notify users about comments, mark comments as read/unread etc.

**Comment by stefandesu** [comment] 2019-12-17 10:01
You're right, it would be easy to just add mapping comments, but without notifications and other things related to it, it doesn't make too much sense. Maybe something like tagging other users would be good as well, e.g. when a certain user downvoted my mapping and I want to ask that user specifically why they did that.

**Comment by stefandesu** [comment] 2021-10-20 11:38
#610 is a duplicate of this, but discussion is further along there, so I'm closing this issue instead.

**Closed as completed by stefandesu** 2021-10-20 11:38 UTC
Labels: feature, question, workflow
