### ISSUE TITLE
Empty creator name when logged in via GitHub?

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#521] opened 2019-11-26 08:17 UTC
A new user, logged in via GitHub created mappings but the creator name ended up empty, e.g. 

https://coli-conc.gbv.de/api/mappings/272d07c2-ed04-4c0e-9564-1e7ec14fbe92

I think the mapping was copied from mapping recommendations. Anyway: if the creator/contributor name is an empty string than don't store it. If no creator/contributor name is given show an (abbreviated) URI instead

**Comment by stefandesu** [comment] 2019-11-26 08:34
Not only did the creator name end up empty, the property `creator` doesn't even exist! And `contributor` has three entries which is super weird as well. I'm going to try to figure this out.

**Comment by stefandesu** [comment] 2019-11-28 03:27
I can't really reproduce what that person has done, but I've found the issue which removed the `creator` property, so this shouldn't happen anymore.

I will keep this open because I've just had an idea how that person could have gotten an empty creator name.

**Comment by stefandesu** [comment] 2019-12-02 03:56
The issue in login-server which has caused the user to have an empty name is now fixed. 👍

**Closed as completed by stefandesu** 2019-12-02 03:56 UTC
Labels: bug
