### ISSUE TITLE
Highlight all mapped/unmapped concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#140] opened 2018-09-14 07:38 UTC
When two concept schemes are selected left and right: load mappings `from` all visible concepts in the left concept scheme to the right concept scheme (`toScheme`) and either highlight all concepts with existing mapping in very light green or highlight all concepts without existing mapping in very light red.

We likely need a setting to toggle on/off this feature and it's mode/color.

**Comment by nichtich** [comment] 2019-04-29 15:42
Concept could be shown with an icon in the concept browser to indicate their current mapping status, e.g.

* concept is mapped
* concept is not mapped
* concept and its children have been mapped up to a given level
* concept is mapped but has unmapped descendants at a given level
* ...

This information would help browsing the hierarchy for subtrees that require mappings.

**Comment by stefandesu** [comment] 2019-09-03 07:53
Duplicate of #458.

**Closed as completed by stefandesu** 2019-09-03 07:53 UTC
Labels: user experience, feature, question
