### ISSUE TITLE
Put registry communication methods into a module

### ISSUE THREAD

**Issue by nichtich** [gbv/cocoda#498] opened 2019-10-02 06:39 UTC
To facilitate creation of additional applications such as gbv/bartoc.org#226 and to add unit tests (#54), all methods that communicate with API endpoints (JSKOS-Server, Skosmos API...) should be put into a node module (#74, maybe `cocoda-sdk`). Given a config file with configuration of registries, it should be  easy to look concepts and mappings without having to know about API endpoints, e.g.:

~~~js
const cdk = require('cocoda-sdk')(config)
const schemes = await cdk.getSchemes()
const concept = await cdk.getConcept({uri})
const mappings = await cdk.getMappings({from, toScheme})
~~~

**Comment by stefandesu** [comment] 2019-12-04 04:23
Duplicate of gbv/cocoda#522 (this one is older, but has less information attached to it, so I'm closing it in favor of the other one).

**Closed as completed by stefandesu** 2019-12-04 04:23 UTC
Labels: question, cleanup
