### ISSUE TITLE
Coli-Conc recommendations incorrect

### ISSUE THREAD

**Issue by DennisTobola** [gbv/cocoda#325] opened 2019-04-03 10:34 UTC
![Screenshot_2019-04-03 Cocoda(1)](https://user-images.githubusercontent.com/37077998/55472598-c965d080-560c-11e9-8fda-ba3127d11114.png)

https://coli-conc.gbv.de/cocoda/dev/?fromScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Frvk%2F&toScheme=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F&from=http%3A%2F%2Frvk.uni-regensburg.de%2Fnt%2FU&to=http%3A%2F%2Furi.gbv.de%2Fterminology%2Fbk%2F7-8 

In this screenshot, when setting the mappings to RVK and BK, the coli-conc recommendations are incorrect. 
Although it is marked with BK and multiple ", it's still obvious, that the recommendations are not only BK, as wanted, but: RVK, Iconclass, BK, RVK, RVK.

**Comment by stefandesu** [comment] 2019-04-03 11:22
Duplicate of #295 (which I reopened).

**Closed as completed by stefandesu** 2019-04-03 11:22 UTC
